### ISSUE TITLE
Failure With Swarm Deployment

### ISSUE THREAD

**Issue by ProfessorMc** [pozgo/docker-mkdocs#4]
The bash script to get IP will fail if you deploy this into a swarm services environment because the IP get shell script returns multiple IP addresses.  This line:

`mkdocs serve -a $(ip addr show eth0 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1):8000 $LRS`

I fixed this by doing the following, which also works fine in the local implementation as well.

`mkdocs serve -a 0.0.0.0:8000 $LRS`

I don't know if there was a specific reason you needed the specific service IP and and port, so I didn't submit this as a PR.

**Comment by pozgo** [comment]
PR #11  fixes this issue
