### ISSUE TITLE
Live upload problem when using diferent port

### ISSUE THREAD

**Issue by KinGsNowGH** [pozgo/docker-mkdocs#47]
As on https://github.com/mkdocs/mkdocs/issues/1175#issuecomment-288096111 we must use the same port on --ports or live upload stops working.
So if possible add environment like 'default_dev_addr' so we can change the default command on mkdocs/common.py 'os.system(f'mkdocs serve -a **0.0.0.0:8000** {_live_reload()} {_fast_mode()}')'.
For now i'm going to edit the file, thanks.

**Comment by pozgo** [comment]
When you edit the file please feel free to submit PR  and I'll merge it.
