### ISSUE TITLE
ARM compatibile?

### ISSUE THREAD

**Issue by voryzen** [pozgo/docker-mkdocs#49]
Is this docker image, compatible with arm architectures, like on a raspberry pi?

**Comment by pozgo** [comment]
Not ATM, but I might find some spare time to add that. It should be as simple as changinf `FROM` to arm based image and rebuild.

**Comment by pozgo** [comment]
I have added steps to ho to build the arm image into readme. And uploaded latest version of mkdocs arm based to Docker Hub https://hub.docker.com/repository/docker/polinux/mkdocs/tags?page=1
