### ISSUE TITLE
Please push arm64 images as well as amd64

### ISSUE THREAD

**Issue by rfay** [pozgo/docker-mkdocs#58]
Currently docker-mkdocs is pushed only as an amd64 image, but that means it gets loaded with the wrong architecture on mac M1 machines. 

Could you please use `docker buildx build` to build and push with both architectures?

**Comment by pozgo** [comment]
Hi @mineblock11 and @rfay 
I have pushed arm-based images manually. I'll try to find some time to add this into the pipeline so it will automatically push those 

https://hub.docker.com/repository/docker/polinux/mkdocs/general

Released 1.4.2 for X64 and Arm

**Comment by rfay** [comment]
Thanks!
