### ISSUE TITLE
Auto-Reload on git based content - triggered on new commit in repository

### ISSUE THREAD

**Issue by stevegroom** [pozgo/docker-mkdocs#7]
Thanks for this docker image - very useful.

I am trying to understand the flow for live reload when cloning a git repo. 

I can see the repo is created when the docker command runs, but I don't see it updating the local repo after that. I was thinking that this should trigger a git pull when the remote is updated. Am I missing something?

Steve

**Comment by pozgo** [comment]
good thinking. I don't think I have added that yet. For now, it's more like the user is responsible to update repo on host OS or inside of docker container. When I have some spare time I might add some hook mechanism to fetch repo

**Comment by pozgo** [comment]
pulling repo feature is going to be removed in the future release since content management should be handled outside of the container. 

Closing
