### ISSUE TITLE
live reload problem

### ISSUE THREAD

**Issue by fglaeser** [pozgo/docker-mkdocs#8]
Hi, if I add the variable LIVE_RELOAD_SUPPORT='true' the reload feature is disabled.
When I checked the bootstrap.sh I found this :

```
    if [[ ${LIVE_RELOAD_SUPPORT} == 'true' ]]; then
        LRS='--no-livereload'
    else
        LRS=''
    fi
```
I think the IF is wrong, if I set the variable in true is because I want the reload support enabled.

If I remove the variable the reload support is enabled.

Best regards.

**Comment by pozgo** [comment]
Fixed with PR #12
